version: "3"
services:
    db:
        container_name: mydb
        image: mariadb
        ports:
            - "3306:3306"
        environment:
            MARIADB_ROOT_PASSWORD: root
            MYSQL_DATABASE: meli
    app:
        container_name: meliapp
        build:
            context: .
            dockerfile: ./app.dockerfile
        ports:
            - "80:80"
    
  


